version: 2

sources:
  - name: sample_data
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: customer
      - name: sales_order
        identifier: orders
      - name: location
        identifier: nation
      - name: region
      - name: part
      - name: supplier
      - name: lineitem
      - name: inventory
        identifier: partsupp
